development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_UR") { "redis://localhost:6379/1" } %>
  channel_prefix: sports_companion_production
